name: Spam Detection Action
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SMS Spam Detection Action
      uses: amaaniqbal/sms-spam-detection@v1.21
      with:
        # Message to be checked for spam
        message: "input message to
